### ISSUE TITLE
Add CLI output to example

### ISSUE THREAD

**Issue by philippgille** [tbiehn/thoughtloom#1]
Hi 👋, I came across your project on https://news.ycombinator.com/item?id=35994037

It's a bit complex maybe, but OTOH seems very powerful for some use cases, especially when doing something repetitively each day or so, or requires data transformation that the AI isn't able to do by itself or require the fine tuning that's possible with the templates. 👍

I noticed in the README there's the example https://github.com/tbiehn/thoughtloom#creating-a-job, but the final output of the tool is missing. With this issue I'm proposing to add the output.

**Comment by tbiehn** [comment]
Good point, that is a totally helpful thing to add.
